language: node_js

node_js:
    - "5.2.0"

branches:
    only:
        - master
        - dev

install:
    - npm install
    - tsd install

script:
    - grunt test

after_success:
    - grunt coverage coveralls
